{% set version = "0.13" %}

package:
  name: xclip
  version: {{ version }}

source:
  url: https://github.com/astrand/xclip/archive/{{ version }}.tar.gz
  sha256: ca5b8804e3c910a66423a882d79bf3c9450b875ac8528791fb60ec9de667f758

build:
  number: 0
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ stdlib('c') }}             # [unix]
    - {{ compiler('c') }}           # [unix]
    - make                          # [unix]
    - autoconf                      # [unix]
    - automake                      # [unix]
    - gettext                       # [unix]
    - libtool                       # [unix]
  host:
    - xorg-libx11
    - xorg-libxmu

test:
  commands:
    - xclip -h

about:
  home: https://github.com/astrand/xclip
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Access X11 clipboards from the command-line
  dev_url: https://github.com/astrand/xclip

extra:
  recipe-maintainers:
    - ehfd
